# Generated by Django 3.2 on 2021-05-02 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_practica', models.CharField(max_length=70)),
                ('fecha', models.DateField(null=True)),
                ('horario', models.CharField(max_length=70)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaslab.area')),
                ('asignatura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaslab.asignatura')),
                ('docente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaslab.docente')),
                ('laboratorio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaslab.laboratorio')),
                ('modalidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaslab.modalidad')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='carrera_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaslab.carrera'),
        ),
    ]
