# Generated by Django 3.2 on 2021-05-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaslab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='carrera_id',
            new_name='carrera',
        ),
        migrations.RenameField(
            model_name='reservaciones',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='reservaciones',
            old_name='asignatura_id',
            new_name='asignatura',
        ),
        migrations.RenameField(
            model_name='reservaciones',
            old_name='docente_id',
            new_name='docente',
        ),
        migrations.RenameField(
            model_name='reservaciones',
            old_name='laboratorio_id',
            new_name='laboratorio',
        ),
        migrations.RenameField(
            model_name='reservaciones',
            old_name='modalidad_id',
            new_name='modalidad',
        ),
    ]
