# Generated by Django 3.2.2 on 2021-05-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaslab', '0003_auto_20210507_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservaslab.turno'),
            preserve_default=False,
        ),
    ]
