# Generated by Django 3.2.2 on 2021-05-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaslab', '0004_reservaciones_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaciones',
            name='horarioFin',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaciones',
            name='horarioInicio',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
